### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 10000
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 100
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "1efe479d45ac417e816caf5200885913",
  "accountNumber": "1000000002",
  "amount": 10000
}

### guery transaction
GET http://localhost:8080/transaction/fa19e534373a4521b2a94126edfcef83
